#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 31 08:29:34 2021

@author: hunglin
"""

import os
import sys
from pathlib import Path
if sys.platform == "linux":
    ffmpeg_path = str(Path(__file__).parent/ f"lib/{sys.platform}/ffmpeg")
elif sys.platform == "win32":
    ffmpeg_path = str(Path(__file__).parent/ f"lib/{sys.platform}/ffmpeg/bin")
os.environ["PATH"] += os.pathsep + ffmpeg_path
from modules.mach import main

if __name__ == "__main__":
    main()